image: Visual Studio 2019
platform:
  - x86
configuration:
  - Release

branches:
  only:
    - master
skip_tags: true

environment:
  matrix:
    - nodejs_version: '12'
    - nodejs_version: '12'
      SPELLCHECKER_PREFER_HUNSPELL: true

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - npm --msvs_version=2019 install

test_script:
  - node --version
  - npm --version
  - ps: Write-Host $env:SPELLCHECKER_PREFER_HUNSPELL
  - npm test

build: off