environment:
  matrix:
    - nodejs_version: '12'
    - nodejs_version: '12'
      SPELLCHECKER_PREFER_HUNSPELL: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm --msvs_version=2015 install

test_script:
  - node --version
  - npm --version
  - ps: Write-Host $env:SPELLCHECKER_PREFER_HUNSPELL
  - npm test

build: off
